<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>txt_Collapse</name>
   <tag></tag>
   <elementGuidId>85b2017c-8d87-4bfc-ad8a-bbef0b578dff</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//td[text()='标准测试1']/..//div[@class='antd-pro-pages-standard-manage-rsm-reference-standard-collapseBox']/div[3]/span[text()='收起']</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
