<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>txt_Expand</name>
   <tag></tag>
   <elementGuidId>70dc5c7e-fa59-4add-85e9-ae24fd8d1d21</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//td[text()='标准测试1']/..//div[@class='antd-pro-pages-standard-manage-rsm-reference-standard-collapseBox']/div[2]/span[text()='展开']</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
